name: deploy
services:
  kafka:
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    image: wurstmeister/kafka
    networks:
      default: null
    ports:
    - mode: ingress
      target: 9092
      published: "9092"
      protocol: tcp
  redis:
    container_name: redis
    image: redis:6.0.7
    networks:
      default: null
    ports:
    - mode: ingress
      target: 6379
      published: "6379"
      protocol: tcp
    restart: always
    volumes:
    - type: volume
      source: redis_volume_data
      target: /data
      volume: {}
  redis_insight:
    container_name: redis_insight
    image: redislabs/redisinsight:latest
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8001
      published: "8001"
      protocol: tcp
    restart: always
    volumes:
    - type: volume
      source: redis_insight_volume_data
      target: /db
      volume: {}
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    networks:
      default: null
    ports:
    - mode: ingress
      target: 2181
      published: "2181"
      protocol: tcp
networks:
  default:
    name: deploy_default
volumes:
  redis_insight_volume_data:
    name: deploy_redis_insight_volume_data
  redis_volume_data:
    name: deploy_redis_volume_data
